### ISSUE TITLE
Lista massas

### ISSUE THREAD

**Issue by ardnaile** [ardnaile/front-end-DeuFome#8]

**Comment by WallaceB2** [comment]
Tela de listas de massas já foi criada, e a tela das receitas de cada massa também já foi criada. Só falta adicionar os caminhos de uma tela para a outra. E após isso o ultimo passo que seria o usuário conseguir adicionar a receita sozinho.

**Comment by WallaceB2** [comment]
Caminhos adicionados! Falta só o usuário conseguir adicionar a receita sozinho.
